language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - psql -c 'create database tests;' -U postgres
  - echo '{"test":{"user":"postgres","password":"","database":"test","host":"localhost","driver":"postgres","protocol":"postgres"}}' > database.json